version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.23.8
    restart: on-failure
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'node1'

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0' # Use CPU

  ollama:
    image: ollama/ollama:latest
    restart: on-failure
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      ENABLE_CUDA: '1'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

volumes:
  ollama:
